name: PresenterLab
favicon: null
layout_spectrum: 0.07487
typography_spectrum: 0.4892878879327327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#b5c6d6'
    - '#d59f85'
    - '#a2745d'
    - '#392f30'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
